version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dp_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-dockerpanel_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./src/DockerPanel.API
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__DockerPanelDb: "Host=db;Port=5432;Username=${POSTGRES_USER:-dp_admin};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB:-dockerpanel_db}"
    ports:
      - "5000:80"
    networks:
      - dockerpanel-net

  nginx:
    image: nginx:alpine
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - dockerpanel-net

volumes:
  pgdata:
    driver: local

networks:
  dockerpanel-net:
    driver: bridge
