version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: dockerpanel-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dp_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-dockerpanel_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dockerpanel-net

  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: dockerpanel-mailserver
    hostname: ${MAIL_HOSTNAME:-mail.burhansahin.com.tr}
    domainname: ${MAIL_DOMAIN:-burhansahin.com.tr}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - /opt/dockerpanel/mail/data:/var/mail
      - /opt/dockerpanel/mail/state:/var/mail-state
      - /opt/dockerpanel/mail/config:/tmp/docker-mailserver
    restart: always
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ONE_DIR=1
    networks:
      - dockerpanel-net

volumes:
  pgdata:
    driver: local

networks:
  dockerpanel-net:
    name: dockerpanel-global-net
    external: true
