with open('src/DockerPanel.Client/Pages/Home.razor', 'rb') as f:
    data = f.read()

# Exact bytes to find and replace (from inspection)
old_bytes = (
    b'        <!-- Sa\xc4\x9f S\xc3\xbctun: SSH Terminal -->\r\n'
    b'        <div class="lg:col-span-2 bg-white border border-[#bbcabf]/30 rounded-xl p-5 flex flex-col h-full shadow-sm min-w-0 overflow-hidden">\r\n'
    b'            <div class="flex items-center justify-between mb-4 border-b border-slate-100 pb-3">\r\n'
    b'                <div class="flex items-center gap-2">\r\n'
    b'                    <span class="w-2.5 h-2.5 rounded-full pulse-green"></span>\r\n'
    b'                    <h3 class="font-bold text-[#0b1c30] text-sm uppercase tracking-wider">Canl\xc4\xb1 Orkestrasyon Loglar\xc4\xb1</h3>\r\n'
    b'                </div>\r\n'
    b'                <button @onclick="ClearTerminal" class="text-xs font-bold text-slate-500 hover:text-slate-700 transition-colors flex items-center gap-1.5">\r\n'
    b'                    <i class="fa-solid fa-trash-can"></i> Terminali Temizle\r\n'
    b'                </button>\r\n'
    b'            </div>\r\n'
    b'\r\n'
    b'            <div class="flex-grow" style="height: 380px; background-color: #f1f5f9 !important; color: #0b1c30 !important; border: 1px solid var(--border-color) !important; font-family: \'JetBrains Mono\', monospace; font-size: 11px; padding: 16px; border-radius: 8px; overflow-y: auto; box-shadow: inset 0 0 10px rgba(0, 0, 0, 0.05);" id="terminal-log-box">\r\n'
    b'                @if (!_systemLogs.Any())\r\n'
    b'                {\r\n'
    b'                    <div style="color: #64748b;">[OK] ApiHub orkestrat\xc3\xb6r izleme mod\xc3\xbcl\xc3\xbc aktif edildi. Ak\xc4\xb1\xc5\x9f dinleniyor...</div>\r\n'
    b'                }\r\n'
    b'                else\r\n'
    b'                {\r\n'
    b'                    @foreach (var log in _systemLogs)\r\n'
    b'                    {\r\n'
    b'                        <div style="margin-bottom: 4px; font-family: \'JetBrains Mono\', monospace; font-size: 11px;">\r\n'
    b'                            <span>@log</span>\r\n'
    b'                        </div>\r\n'
    b'                    }\r\n'
    b'                }\r\n'
    b'            </div>\r\n'
    b'\r\n'
    b'            <!-- Terminal Komut Giri\xc5\x9f Alan\xc4\xb1 -->\r\n'
    b'            <div class="mt-3 flex items-center border border-slate-200 rounded-lg bg-[#f1f5f9] px-3 py-1 font-mono text-xs">\r\n'
    b'                <span class="text-slate-500 mr-2">$</span>\r\n'
    b'                <input @bind="_terminalCommand" @onkeydown="HandleTerminalKeyDown" class="flex-grow bg-transparent border-none outline-none text-[#0b1c30] p-1.5 focus:ring-0" placeholder="Konteyner komutu girin..." />\r\n'
    b'                @if (_isExecutingCommand)\r\n'
    b'                {\r\n'
    b'                    <span class="w-4 h-4 border-2 border-[#0b1c30] border-t-transparent rounded-full animate-spin flex-shrink-0 ml-2"></span>\r\n'
    b'                }\r\n'
    b'            </div>\r\n'
    b'        </div>\r\n'
    b'    </div>'
)

new_bytes = (
    b'        <!-- Sa\xc4\x9f S\xc3\xbctun: SSH Terminal -->\r\n'
    b'        <div class="lg:col-span-2 rounded-xl flex flex-col h-full min-w-0 overflow-hidden shadow-xl" style="background:#0d1117; border:1px solid #30363d;">\r\n'
    b'            <!-- Terminal Ba\xc5\x9fl\xc4\xb1k \xc3\x87ubu\xc4\x9fu -->\r\n'
    b'            <div class="flex items-center justify-between px-4 py-2.5 border-b" style="background:#161b22; border-color:#30363d;">\r\n'
    b'                <div class="flex items-center gap-1.5">\r\n'
    b'                    <span class="w-3 h-3 rounded-full inline-block" style="background:#ff5f57;"></span>\r\n'
    b'                    <span class="w-3 h-3 rounded-full inline-block" style="background:#febc2e;"></span>\r\n'
    b'                    <span class="w-3 h-3 rounded-full inline-block" style="background:#28c840;"></span>\r\n'
    b'                    <span class="ml-4 text-xs font-mono" style="color:#8b949e;">root&#64;apiserver: ~</span>\r\n'
    b'                </div>\r\n'
    b'                <div class="flex items-center gap-3">\r\n'
    b'                    <span class="flex items-center gap-1.5 text-[10px] font-mono" style="color:#3fb950;">\r\n'
    b'                        <span class="w-1.5 h-1.5 rounded-full animate-pulse" style="background:#3fb950;"></span>\r\n'
    b'                        SSH BA\xc4\x9eLANDI\r\n'
    b'                    </span>\r\n'
    b'                    <button @onclick="ClearTerminal" class="text-[10px] font-mono hover:opacity-75 transition-opacity flex items-center gap-1" style="color:#8b949e;">\r\n'
    b'                        <i class="fa-solid fa-eraser text-[9px]"></i> Temizle\r\n'
    b'                    </button>\r\n'
    b'                </div>\r\n'
    b'            </div>\r\n'
    b'\r\n'
    b'            <!-- Terminal \xc3\x87\xc4\xb1kt\xc4\xb1 Alan\xc4\xb1 -->\r\n'
    b'            <div class="flex-grow overflow-y-auto px-4 py-3 font-mono text-xs leading-relaxed" id="ssh-terminal-output"\r\n'
    b'                 style="background:#0d1117; color:#c9d1d9; min-height:320px; max-height:380px;">\r\n'
    b'                @if (!_sshHistory.Any())\r\n'
    b'                {\r\n'
    b'                    <div class="mb-1" style="color:#8b949e;">Welcome to Ubuntu 22.04 LTS (GNU/Linux x86_64)</div>\r\n'
    b'                    <div class="mb-3" style="color:#8b949e;">Komut girin ve Enter\'a bas\xc4\xb1n...</div>\r\n'
    b'                }\r\n'
    b'                @foreach (var entry in _sshHistory)\r\n'
    b'                {\r\n'
    b'                    @if (entry.IsCommand)\r\n'
    b'                    {\r\n'
    b'                        <div class="flex items-center gap-0 mb-0.5">\r\n'
    b'                            <span style="color:#3fb950; white-space:nowrap; flex-shrink:0;">root&#64;apiserver</span><span style="color:#8b949e; flex-shrink:0;">:</span><span style="color:#58a6ff; flex-shrink:0;">~</span><span style="color:#e6edf3; flex-shrink:0;" class="mr-1.5">$</span>\r\n'
    b'                            <span style="color:#e6edf3; word-break:break-all;">@entry.Text</span>\r\n'
    b'                        </div>\r\n'
    b'                    }\r\n'
    b'                    else\r\n'
    b'                    {\r\n'
    b'                        <div class="mb-0.5 whitespace-pre-wrap break-words" style="color:@(entry.IsError ? &quot;#ff7b72&quot; : &quot;#c9d1d9&quot;);">@entry.Text</div>\r\n'
    b'                    }\r\n'
    b'                }\r\n'
    b'                @if (_isExecutingCommand)\r\n'
    b'                {\r\n'
    b'                    <div class="flex items-center gap-1.5 mt-1" style="color:#8b949e;">\r\n'
    b'                        <span class="w-3 h-3 border border-current border-t-transparent rounded-full animate-spin inline-block" style="flex-shrink:0;"></span>\r\n'
    b'                        <span>&#x00e7;al\xc4\xb1\xc5\x9ft\xc4\xb1r\xc4\xb1l\xc4\xb1yor...</span>\r\n'
    b'                    </div>\r\n'
    b'                }\r\n'
    b'            </div>\r\n'
    b'\r\n'
    b'            <!-- Komut Giri\xc5\x9f Sat\xc4\xb1r\xc4\xb1 -->\r\n'
    b'            <div class="flex items-center px-4 py-2.5 border-t font-mono text-xs" style="background:#161b22; border-color:#30363d;">\r\n'
    b'                <span style="color:#3fb950; white-space:nowrap; flex-shrink:0;">root&#64;apiserver</span>\r\n'
    b'                <span style="color:#8b949e; flex-shrink:0;">:</span>\r\n'
    b'                <span style="color:#58a6ff; flex-shrink:0;">~</span>\r\n'
    b'                <span style="color:#e6edf3; flex-shrink:0;" class="mr-2">$</span>\r\n'
    b'                <input @bind="_terminalCommand"\r\n'
    b'                       @bind:event="oninput"\r\n'
    b'                       @onkeydown="HandleTerminalKeyDown"\r\n'
    b'                       id="ssh-input"\r\n'
    b'                       class="flex-grow bg-transparent border-none outline-none focus:ring-0 min-w-0"\r\n'
    b'                       style="color:#e6edf3; caret-color:#58a6ff; font-family:\'JetBrains Mono\',monospace; font-size:12px;"\r\n'
    b'                       autocomplete="off"\r\n'
    b'                       spellcheck="false" />\r\n'
    b'            </div>\r\n'
    b'        </div>\r\n'
    b'    </div>'
)

if old_bytes in data:
    data = data.replace(old_bytes, new_bytes, 1)
    print('SUCCESS: Block replaced!')
else:
    print('FAIL: Block not found')
    import sys
    sys.exit(1)

with open('src/DockerPanel.Client/Pages/Home.razor', 'wb') as f:
    f.write(data)
print('File saved.')
